import { type ComponentType, type SVGProps, createElement } from "react";
import {
  SiAnthropic,
  SiCss,
  SiCypress,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiFramer,
  SiGit,
  SiGithubactions,
  SiGo,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiRust,
  SiSass,
  SiSupabase,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVitest,
  SiVuedotjs,
  SiC,
  SiCplusplus,
  SiElectron,
  SiBootstrap,
  SiMui,
  SiAntdesign,
  SiShadcnui,
  SiPwa,
  SiSocketdotio,
  SiServerless,
  SiSequelize,
  SiSqlalchemy,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiRabbitmq,
  SiJenkins,
  SiSwagger,
  SiJira,
  SiTrello,
  SiPostman,
  SiMocha,
  SiGithubcopilot,
  SiCursor,
  SiCoursera,
  SiUdemy,
  SiGoogle,
} from "react-icons/si";
import { FaAws, FaMicrosoft } from "react-icons/fa6";
import { TbBrandOpenai, TbBrandVscode, TbBrandAmazon } from "react-icons/tb";
import {
  Code2,
  Database,
  Server,
  TestTube2,
  Brain,
  Cloud,
  type LucideProps,
  Workflow,
  Boxes,
  Network,
  Zap,
  Layers,
  ListTodo,
  CheckCircle2,
  Eye,
  Gauge,
  RotateCcw,
  Users,
} from "lucide-react";

export type SkillIconProps = SVGProps<SVGSVGElement> & {
  className?: string;
  size?: string | number;
};

type IconComponent = ComponentType<SkillIconProps | LucideProps>;

const SKILL_ICON_MAP: Record<string, IconComponent> = {
  // Languages
  typescript: SiTypescript,
  ts: SiTypescript,
  javascript: SiJavascript,
  js: SiJavascript,
  python: SiPython,
  go: SiGo,
  golang: SiGo,
  rust: SiRust,
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss,
  css3: SiCss,
  sass: SiSass,
  scss: SiSass,
  sql: Database,
  c: SiC,
  cplusplus: SiCplusplus,
  cpp: SiCplusplus,

  // Frontend
  react: SiReact,
  reactjs: SiReact,
  next: SiNextdotjs,
  nextjs: SiNextdotjs,
  nextdotjs: SiNextdotjs,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  vuedotjs: SiVuedotjs,
  redux: SiRedux,
  reduxtoolkit: SiRedux,
  reduxthunk: SiRedux,
  reduxsaga: SiRedux,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  framer: SiFramer,
  framermotion: SiFramer,
  electron: SiElectron,
  electronjs: SiElectron,
  bootstrap: SiBootstrap,
  mui: SiMui,
  materialui: SiMui,
  antdesign: SiAntdesign,
  antd: SiAntdesign,
  shadcnui: SiShadcnui,
  shadcn: SiShadcnui,
  pwa: SiPwa,

  // Backend & APIs
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  nodedotjs: SiNodedotjs,
  express: SiExpress,
  expressjs: SiExpress,
  nest: SiNestjs,
  nestjs: SiNestjs,
  django: SiDjango,
  flask: SiFlask,
  fastapi: SiFastapi,
  graphql: SiGraphql,
  prisma: SiPrisma,
  restapis: Code2,
  restapi: Code2,
  apigateway: Server,
  websockets: SiSocketdotio,
  socketio: SiSocketdotio,
  serverless: SiServerless,
  server: Server,

  // Databases & ORMs
  mongodb: SiMongodb,
  mongo: SiMongodb,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mysql: SiMysql,
  redis: SiRedis,
  firebase: SiFirebase,
  supabase: SiSupabase,
  database: Database,
  dynamodb: TbBrandAmazon,
  dynamo: TbBrandAmazon,
  sequelize: SiSequelize,
  sequelizeorm: SiSequelize,
  sqlalchemy: SiSqlalchemy,

  // DevOps & Cloud
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  githubactions: SiGithubactions,
  linux: SiLinux,
  cloud: Cloud,
  aws: FaAws,
  amazonwebservices: FaAws,
  cicd: Workflow,
  jenkins: SiJenkins,

  // AI / ML & Tools
  tensorflow: SiTensorflow,
  anthropic: SiAnthropic,
  ai: Brain,
  ml: Brain,
  brain: Brain,
  openai: TbBrandOpenai,
  openaigpt4api: TbBrandOpenai,
  promptengineering: Zap,
  githubcopilot: SiGithubcopilot,
  cursor: SiCursor,
  cursorai: SiCursor,
  playfab: props => createElement(FaMicrosoft, props as any),

  // Testing & Quality
  jest: SiJest,
  vitest: SiVitest,
  cypress: SiCypress,
  testing: TestTube2,
  test: TestTube2,
  unittest: CheckCircle2,
  unittesting: CheckCircle2,
  tdd: CheckCircle2,
  mocha: SiMocha,
  swagger: SiSwagger,
  swaggeropenapi: SiSwagger,
  codereviews: Eye,
  performanceoptimization: Gauge,

  // Tools & Methods
  agile: RotateCcw,
  agilescrum: RotateCcw,
  jira: SiJira,
  trello: SiTrello,
  postman: SiPostman,
  vscode: TbBrandVscode,
  dsa: Code2,
};

export function normalizeSkillIconKey(iconKey: string): string {
  return iconKey.toLowerCase().replace(/[\s._+/-]/g, "");
}

export function getSkillIcon(iconKey: string): IconComponent {
  const normalized = normalizeSkillIconKey(iconKey);
  return SKILL_ICON_MAP[normalized] ?? Code2;
}

